import { Preset } from "./types";

export const PRESETS: Record<string, Preset> = {
  tuned: {
    label: "★ Tuned",
    description: "Ottimale",
    variant: "tuned",
    population_size: 81,
    tournament_size: 4,
    elite_count: 4,
    granular_size: 25,
    mutation_rate: 0.236,
    crossover_rate: 0.675,
    local_search_rate: 0.259,
    local_search_max_iter: 10,
  },
  large: {
    label: "Large",
    description: "Qualità",
    variant: "best",
    population_size: 100,
    tournament_size: 4,
    elite_count: 5,
    granular_size: 15,
    mutation_rate: 0.1,
    crossover_rate: 0.8,
    local_search_rate: 0.1,
    local_search_max_iter: 2,
  },
  balanced: {
    label: "Balanced",
    description: "Equilibrio",
    variant: "balanced",
    population_size: 60,
    tournament_size: 3,
    elite_count: 4,
    granular_size: 12,
    mutation_rate: 0.1,
    crossover_rate: 0.85,
    local_search_rate: 0.1,
    local_search_max_iter: 2,
  },
  medium: {
    label: "Medium",
    description: "Medio",
    variant: "accent",
    population_size: 30,
    tournament_size: 3,
    elite_count: 3,
    granular_size: 7,
    mutation_rate: 0.1,
    crossover_rate: 0.8,
    local_search_rate: 0.1,
    local_search_max_iter: 2,
  },
  small: {
    label: "Small",
    description: "Leggero",
    variant: "small-preset",
    population_size: 10,
    tournament_size: 2,
    elite_count: 2,
    granular_size: 3,
    mutation_rate: 0.1,
    crossover_rate: 0.8,
    local_search_rate: 0.1,
    local_search_max_iter: 2,
  },
  fast: {
    label: "Fast",
    description: "Velocità",
    variant: "warning",
    population_size: 5,
    tournament_size: 2,
    elite_count: 1,
    granular_size: 2,
    mutation_rate: 0.1,
    crossover_rate: 0.8,
    local_search_rate: 0.1,
    local_search_max_iter: 2,
  },
  explore: {
    label: "Explore",
    description: "Esplora",
    variant: "danger",
    population_size: 100,
    tournament_size: 2,
    elite_count: 1,
    granular_size: 15,
    mutation_rate: 0.4,
    crossover_rate: 0.95,
    local_search_rate: 0.25,
    local_search_max_iter: 3,
  },
};

export const ROUTE_COLORS = [
  "#6c8cff", "#4ade80", "#fbbf24", "#f87171", "#a78bfa",
  "#22d3ee", "#fb923c", "#f472b6", "#34d399", "#e879f9",
  "#818cf8", "#2dd4bf", "#facc15", "#fb7185", "#38bdf8",
  "#a3e635", "#c084fc", "#60a5fa", "#f59e0b", "#10b981",
];
